export const FORMAT_DATE = {
  YYYY_MM_DD: 'YYYY-MM-DD',
  YYYY_MM_DD_HH_mm_ss: 'YYYY-MM-DD HH:mm:ss',
  YYYY_MM_DD_HH_mm: 'YYYY-MM-DD HH:mm',

  DD_MM_YY: 'DD MM YY',
  DD_MMM_YY: 'DD MMM YY',
  DD_MMM_YY_H_m: 'DD MMM YY H:m',
  DD_MMM_YY_H_mm: 'DD MMM YY H:mm',
  HH_mm: 'HH:mm:ss',
  MM_DD_YYYY: 'MM-DD-YYYY',
  DD_MM_YYYY: 'DD-MM-YYYY',
  YYYY_MM_DD_H_m: 'YYYY-MM-DD H:m',
  MM_DD_YYYY_H_m: 'MM-DD-YYYY H:m',
  DD_MM_YYYY_H_m: 'DD-MM-YYYY H:m',
  DD_MMMM_YYYY_hh_mm_A: 'DD MMMM YYYY, hh:mm A',
  DD_MMM_YYYY_hh_mm_A: 'DD MMM YYYY, hh:mm A',
  hh_mm_A: 'hh:mm A',
  DD_MMM_YY_h_mm_A: 'DD MMM YY, h:mm A',
  HH_MM: 'HH:mm',
  MMMM_YYYY: 'MMMM YYYY',
  h_mm_a: 'h:mm A',
  MM_YYYY: 'MMM-YYYY',
  DD_MMM_YYYY: 'DD MMM YYYY',
  dddd_DD_MMM_YY: 'dddd, DD MMM YY',
  dddd: 'dddd',
  D_MMMM_YYYY: 'D MMMM YYYY',
  DD_MMMM_YY: 'DD MMMM YY',
  DD_MMMM_YYYY: 'DD MMMM YYYY',
  D_MMM_YYYY: 'D MMM YYYY',
  DD_MMM_YY_h_mm_A_2: 'DD MMM YY @ h:mm A',
  DD_MMMM_YYYY_AT_h_mm_a: 'DD MMM YY [at] h:mm A',
  DD_MM_YYYY_hh_mm: 'DD_MM_YYYY_hh_mm'
}
